name: Build & Deploy Master

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: |
        sudo apt-get update
        sudo apt-get install musl-tools
        rustup target add x86_64-unknown-linux-musl
        cd rendering-envs
        ./setup.sh
        cd ../
    - name: Create version.txt
      run: |
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        git_branch=${GITHUB_REF#refs/heads/}
        echo "$git_branch-$git_hash" > version.txt
        echo "GIT_BRANCH=$git_branch" >> $GITHUB_ENV
        echo "GIT_HASH=$git_hash" >> $GITHUB_ENV
    - name: Build x86_64-unknown-linux-gnu
      run: cargo build --release --verbose --target x86_64-unknown-linux-gnu
    - name: Build x86_64-unknown-linux-musl
      run: cargo build --release --verbose --target x86_64-unknown-linux-musl
    - name: Run tests
      run: cargo test --release --verbose
    - name: Package artifact x86_64-unknown-linux-gnu
      run: |
        mkdir packaged
        cp target/x86_64-unknown-linux-gnu/release/PublishGoods-Rendering-Server packaged/ 
        mkdir packaged/config && mkdir packaged/rendering-envs && mkdir packaged/templates 
        cp -R rendering-envs/* packaged/rendering-envs
        cp config/default.toml packaged/config/
        cp version.txt packaged/ 
        cd packaged
        tar -vczf ../publishgoods-rendering-server-bundled-x86_64-unknown-linux-gnu.tar.gz *
    - uses: actions/upload-artifact@v4
      with:
        name: publishgoods-rendering-server-x86_64-unknown-linux-gnu
        path: publishgoods-rendering-server-bundled-x86_64-unknown-linux-gnu.tar.gz
    - name: Package artifact x86_64-unknown-linux-musl
      run: |
        mkdir packaged-musl
        cp target/x86_64-unknown-linux-musl/release/PublishGoods-Rendering-Server packaged-musl/ 
        mkdir packaged-musl/config && mkdir packaged-musl/rendering-envs && mkdir packaged-musl/templates 
        cp -R rendering-envs/* packaged-musl/rendering-envs
        cp config/default.toml packaged-musl/config/
        cp version.txt packaged-musl/ 
        cd packaged-musl
        tar -vczf ../publishgoods-rendering-server-bundled-x86_64-unknown-linux-musl.tar.gz *
    - uses: actions/upload-artifact@v4
      with:
        name: publishgoods-rendering-server-x86_64-unknown-linux-musl
        path: publishgoods-rendering-server-bundled-x86_64-unknown-linux-musl.tar.gz
    - uses: softprops/action-gh-release@v2
      with:
        files: |
          publishgoods-rendering-server-bundled-x86_64-unknown-linux-gnu.tar.gz
          publishgoods-rendering-server-bundled-x86_64-unknown-linux-musl.tar.gz
        name: "${{ env.GIT_BRANCH }}-${{ env.GIT_HASH }}"
        tag_name: "${{ env.GIT_BRANCH }}-${{ env.GIT_HASH }}"
        draft: true
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: publishgoods-rendering-server-x86_64-unknown-linux-gnu
          path: dest
      - name: List dest
        run: ls -R dest
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.STAGING_SSH_KEY }}" > ~/.ssh/staging_ssh_key
          chmod 600 ~/.ssh/*
          ssh-keyscan -t ed25519 editor-staging-rendering1.verfassungsblog.de >> ~/.ssh/known_hosts
      - name: Cleanup staging server files
        run: | 
          ssh -i ~/.ssh/staging_ssh_key -t verfassungsbooks@editor-staging-rendering1.verfassungsblog.de "sudo systemctl stop rendering-server.service"
      - name: Upload artifact to staging server
        run: scp -i ~/.ssh/staging_ssh_key dest/publishgoods-rendering-server-bundled-x86_64-unknown-linux-gnu.tar.gz verfassungsbooks@editor-staging-rendering1.verfassungsblog.de:/home/verfassungsbooks/verfassungsbooks-rendering-server-bundled.tar.gz
      - name: Start update and start staging server
        run: |
          ssh -i ~/.ssh/staging_ssh_key -t verfassungsbooks@editor-staging-rendering1.verfassungsblog.de "cd /home/verfassungsbooks && ./update.sh verfassungsbooks-rendering-server-bundled.tar.gz rendering-server"
          ssh -i ~/.ssh/staging_ssh_key -t verfassungsbooks@editor-staging-rendering1.verfassungsblog.de "sudo systemctl start rendering-server.service"
